yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.index, name='homepage'),
    path('posts/', views.group_posts, name='group_list')

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()


class Group(models.Model):
    title = models.TextField()
    slug = models.SlugField(default='some string')
    description = models.CharField(max_length=10000, default='some string')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, blank=True, null=True,
                              on_delete=models.CASCADE,
                              related_name='posts')

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Post, Group

# Create your views here.


def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    # В словаре context отправляем информацию в шаблон
    context = {
        'posts': posts,
        'title': 'Последние обновления на сайте',
    }
    return render(request, 'posts/index.html', context)


# Create your views here.
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,

    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <title>{{ title }}</title>
  </head>
  <body>
    <header>
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->    
      {% include 'includes/header.html' %}
    </header>
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>{{ text }}</h1>
        {% for post in posts %}
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
        </ul>
        <p>{{ post.text }}</p>    
            
            <a href="{% url 'posts:group_list' %}">все записи группы</a>
            
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        <!-- под последним постом нет линии -->
      </div>  
    </main>
    <footer class="page-footer font-small blue border-top">
      <{% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:homepage' %}">
        {% load static %}
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
        <span style="color:red">Ya</span>tube
      </a>
    </div>
  </nav>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
<title>Записи сообщества {{ group }}</title>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
{% endblock %}